name: Automation

on:
  push:
    branches:
      - main
      - develop
  
  pull_request:
    branches:
      - main
      - develop

jobs:
  code-testing:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run : uv sync
      - name: Run tests
        run: uv run --frozen pytest --maxfail=1 --disable-warnings -q 
      
      - name: Run and generate coverage
        run: |
          uv run --frozen coverage run -m pytest
          uv run --frozen coverage report
          uv run --frozen coverage html -d coverage_report
        
      - name: Upload coverage report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report

  generate-documentation:
    needs: code-testing
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run : uv sync

      - name: Build Sphinx documentation
        run: |
          cd docs
          uv run --frozen sphinx-apidoc -o ./source ../ppft
          uv run --frozen make html
          
      - name: Upload documentation as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/build/html
