name: Automation

on:
  push:
    branches:
      - main
      - develop
  
  pull_request:
    branches:
      - main
      - develop

jobs:
  building-project:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install project
        run: uv sync

      - name: Save virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: .\\venv

  code-testing:
    needs: building-project
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
        
      - uses: actions/download-artifact@v4
        with:
          name: venv
          path: .\\venv

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q
      
      - name: Run and generate coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage report
          uv run coverage html -d coverage_report
        
      - name: Upload coverage report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report


  generate-documentation:
    needs: [building-project, code-testing]
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
        
      - uses: actions/download-artifact@v4
        with:
          name: venv
          path: .\\venv

      - name: Build Sphinx documentation
        run: |
          cd docs
          uv run sphinx-apidoc -o ./source ../ppft
          make html
          
      - name: Upload documentation as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/build/html
