name: Development

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
    push:

    workflow_call:

jobs:
    build-env:
        name: Python
        runs-on: windows-latest

        steps:
            - name: Setup Environment
              uses: ./workflows/setup_code.yaml@feature-loan-calculator

            - name: Testing
              run: uv run pytest


    # Lint:
    #     needs: build-env
    #     name: Linting
    #     runs-on: windows-latest

    #     steps:
    #         - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    #         - name: Install uv
    #           uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca  # v6.0.1
    #           with:
    #             version: "0.7.2"
    #             enable-cache: true
            
    #         - name: Install
    #           run: uv sync --locked --all-extras

    #         - name: Lint
    #           run: uv run mypy pfts

